version: '3.9'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaiv
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    container_name: mariadb-vaiv
    volumes:
      - ./db/mysql/data:/var/lib/mysql